puts "generating react-routes.js"

content = %q(// WARNING: DO NOT MODIFY!!!
//
// This file is automatically generated by config/initializers/react_routes.rb.
// Any manual modifications to this file will be overwritten when the application initializes.

var React = require('react');
var ReactDOM = require('react-dom');
var views = {};

window.ReactViewEngine = {
  render: function(controller, action, model, target){
    var View = views[controller][action].default;
    ReactDOM.render(<View {...model}/>, target);
  }
};

)


dirs = Dir["app/assets/javascripts/views/*/"]
dirs.each{ |dir|
  dir = dir[0...-1]
  controller = dir[dir.rindex('/')+1..-1]
  content << "views.#{controller} = {\n"
  actionDirs = Dir["#{dir}/*.js"]
  actionDirs.each{ |actionDir|
    action = actionDir[actionDir.rindex('/')+1..-1]
    action[".js"] = ""
    content << "\t#{action}: require('./#{controller}/#{action}'),\n"
  }
  content << "};\n"
}

filename = "app/assets/javascripts/views/react-routes.js"
File.open(filename, "w") {|f| f.write(content) }
puts "updated react-routes.js"